cursor #e2e2e3
cursor_text_color #c1c7cc

foreground            #e2e2e3
background            #121415
selection_foreground  #253239
selection_background  #bbc9d1
url_color             #a7cce0

color0   #121415
color1   #ff729f
color2   #70e07d
color3   #fff672
color4   #93bdd4
color5   #375667
color6   #a7cce0
color7   #dde6eb
color8   #868d91
color9   #ff9fbd
color10  #a5ffb0
color11  #fff9a5
color12  #c1e3f6
color13  #d1efff
color14  #e1f4ff
color15  #f8fcff
