cursor #e1e2ec
cursor_text_color #c2c6d6

foreground            #e1e2ec
background            #11131a
selection_foreground  #192f5c
selection_background  #b2c6fc
url_color             #b1c6ff

color0   #11131a
color1   #ff7298
color2   #7fff93
color3   #fff872
color4   #99b1f2
color5   #334576
color6   #b1c6ff
color7   #eff3ff
color8   #999ca5
color9   #ff9fb9
color10  #a5ffb3
color11  #fffba5
color12  #bcceff
color13  #c8d7ff
color14  #dbe5ff
color15  #f8faff
