# Colors (Noctalia)

[colors.bright]
black = '#3e4042'
blue = '#acc6c9'
cyan = '#acc9bc'
green = '#b0cc9d'
magenta = '#d1b1cc'
red = '#e58e8e'
white = '#e5dfd9'
yellow = '#e6ccb1'

[colors.cursor]
cursor = '#cdc5bd'
text = '#1a1b1c'

[colors.normal]
black = '#1a1b1c'
blue = '#8faeb1'
cyan = '#8fb8a7'
green = '#91ad83'
magenta = '#b892b1'
red = '#db6d6d'
white = '#cdc5bd'
yellow = '#d1b394'

[colors.primary]
background = '#1a1b1c'
foreground = '#cdc5bd'

[colors.selection]
background = '#db6d6d'
text = '#1a1b1c'
