[colors.primary]
background = '#181210'
foreground = '#ede0db'
 
[colors.cursor]
text = '#ede0db'
cursor = '#d8c2ba' 
 
[colors.vi_mode_cursor]
text = '#181210'
cursor = '#ffb695' 
 
[colors.search.matches]
foreground = '#52443d' 
background = '#d1c88f' 
 
[colors.search.focused_match]
foreground = '#52443d' 
background = '#ffb695' 
 
[colors.footer_bar]
foreground = '#52443d' 
background = '#ede0db' 
 
[colors.hints.start]
foreground = '#52443d' 
background = '#e6bead' 
 
[colors.hints.end]
foreground = '#52443d' 
background = '#e6bead' 
 
[colors.selection]
text = '#181210'
background = '#ffb695'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#ffb695' 
yellow = '#99461b' 
blue = '#ffb695' 
magenta = '#d1c88f' 
cyan = '#e6bead' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 