[general]
import = [
    "~/.config/alacritty/themes/themes/rose_pine.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "none"
# opacity = 0.7
opacity = 0.85


[font] 
size = 17

[font.normal]
family =  "SauceCodePro Nerd Font"

[[keyboard.bindings]]
key = "F11"
action = "ToggleFullscreen"

# [[keyboard.bindings]]
# key = "v"
# mods = "Control"
# action = "Paste"
