[colors.primary]
background = '#11131a'
foreground = '#e1e2ec'

[colors.selection]
text = '#e1e2ec'
background = '#1160da'

[colors.cursor]
text = '#11131a'
cursor = '#b1c6ff'

[colors.normal]
black   = '#11131a'
red     = '#ff7298'
green   = '#7fff93'
yellow  = '#fff872'
blue    = '#99b1f2'
magenta = '#334576'
cyan    = '#b1c6ff'
white   = '#eff3ff'

[colors.bright]
black   = '#999ca5'
red     = '#ff9fb9'
green   = '#a5ffb3'
yellow  = '#fffba5'
blue    = '#bcceff'
magenta = '#c8d7ff'
cyan    = '#dbe5ff'
white   = '#f8faff'
