[colors.primary]
background = '#121415'
foreground = '#e2e2e3'

[colors.selection]
text = '#e2e2e3'
background = '#3c6071'

[colors.cursor]
text = '#121415'
cursor = '#a7cce0'

[colors.normal]
black   = '#121415'
red     = '#ff729f'
green   = '#70e07d'
yellow  = '#fff672'
blue    = '#93bdd4'
magenta = '#375667'
cyan    = '#a7cce0'
white   = '#dde6eb'

[colors.bright]
black   = '#868d91'
red     = '#ff9fbd'
green   = '#a5ffb0'
yellow  = '#fff9a5'
blue    = '#c1e3f6'
magenta = '#d1efff'
cyan    = '#e1f4ff'
white   = '#f8fcff'
